// <auto-generated />
using System;
using AP.BTP.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AP.BTP.Infrastructure.Migrations
{
    [DbContext(typeof(BTPContext))]
    [Migration("20251220160227_finalMigration")]
    partial class finalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AP.BTP.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Address", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HouseNumber = "A22",
                            PostalCode = "2140",
                            StreetName = "teststraat"
                        });
                });

            modelBuilder.Entity("AP.BTP.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#111999",
                            IsArchived = false,
                            Name = "Watergeven"
                        });
                });

            modelBuilder.Entity("AP.BTP.Domain.EmployeeTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PlannedDuration")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlannedStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StopTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TaskListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.HasIndex("StopTime");

                    b.HasIndex("TaskListId");

                    b.HasIndex("TaskListId", "Order");

                    b.ToTable("EmployeeTask");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Dit is taak 1",
                            Order = 1,
                            PlannedDuration = 2,
                            PlannedStartTime = new DateTime(2025, 10, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 10, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            StopTime = new DateTime(2025, 10, 1, 11, 30, 0, 0, DateTimeKind.Utc),
                            TaskListId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Dit is taak 2",
                            Order = 2,
                            PlannedDuration = 1,
                            PlannedStartTime = new DateTime(2025, 10, 1, 13, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 10, 1, 13, 0, 0, 0, DateTimeKind.Utc),
                            StopTime = new DateTime(2025, 10, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            TaskListId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Dit is taak 3",
                            Order = 3,
                            PlannedDuration = 3,
                            PlannedStartTime = new DateTime(2025, 10, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 10, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            StopTime = new DateTime(2025, 10, 1, 18, 0, 0, 0, DateTimeKind.Utc),
                            TaskListId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Dit is taak 4",
                            Order = 1,
                            PlannedDuration = 1,
                            PlannedStartTime = new DateTime(2025, 11, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 11, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            StopTime = new DateTime(2025, 11, 11, 10, 30, 0, 0, DateTimeKind.Utc),
                            TaskListId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Dit is taak 5",
                            Order = 2,
                            PlannedDuration = 1,
                            PlannedStartTime = new DateTime(2025, 11, 11, 11, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 11, 11, 11, 0, 0, 0, DateTimeKind.Utc),
                            StopTime = new DateTime(2025, 11, 11, 12, 30, 0, 0, DateTimeKind.Utc),
                            TaskListId = 2
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Dit is taak 6",
                            Order = 3,
                            PlannedDuration = 1,
                            PlannedStartTime = new DateTime(2025, 11, 11, 13, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 11, 11, 13, 0, 0, 0, DateTimeKind.Utc),
                            StopTime = new DateTime(2025, 11, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            TaskListId = 2
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Dit is taak 7",
                            Order = 4,
                            PlannedDuration = 1,
                            PlannedStartTime = new DateTime(2025, 11, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 11, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            StopTime = new DateTime(2025, 11, 12, 9, 30, 0, 0, DateTimeKind.Utc),
                            TaskListId = 3
                        });
                });

            modelBuilder.Entity("AP.BTP.Domain.GroundPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("GroundPlan", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileUrl = "/test/file",
                            UploadTime = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("AP.BTP.Domain.Instruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("instructieId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("bestandUrl");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("seizoen");

                    b.Property<int>("TreeTypeId")
                        .HasColumnType("int")
                        .HasColumnName("boomSoortId");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("date")
                        .HasColumnName("uploadTijd");

                    b.HasKey("Id");

                    b.HasIndex("TreeTypeId");

                    b.ToTable("Instruction", (string)null);
                });

            modelBuilder.Entity("AP.BTP.Domain.NurserySite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("GroundPlanId")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("GroundPlanId")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NurserySite", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            GroundPlanId = 1,
                            IsArchived = false,
                            Name = "Site 1",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("AP.BTP.Domain.TaskList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("UserId");

                    b.HasIndex("ZoneId");

                    b.ToTable("TaskList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            UserId = 2,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("AP.BTP.Domain.TreeImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TreeTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TreeTypeId");

                    b.ToTable("TreeImages");
                });

            modelBuilder.Entity("AP.BTP.Domain.TreeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsArchived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("QrCodeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("TreeType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Testbeschrijving",
                            IsArchived = false,
                            Name = "Haagbeuk"
                        });
                });

            modelBuilder.Entity("AP.BTP.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PreferredNurserySiteId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PreferredNurserySiteId");

                    b.ToTable("UserList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthId = "6910ac6f6749b5a63269405d",
                            Email = "testadmin@test.com",
                            FirstName = "FirstAdmin",
                            LastName = "LastAdmin",
                            Username = "TestAdmin"
                        },
                        new
                        {
                            Id = 2,
                            AuthId = "6910b5346749b5a6326942b8",
                            Email = "testmedewerker@test.com",
                            FirstName = "FirstMedewerker",
                            LastName = "LastMedewerker",
                            Username = "TestMedewerker"
                        });
                });

            modelBuilder.Entity("AP.BTP.Domain.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Role = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Role = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("AP.BTP.Domain.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NurserySiteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("TreeTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("NurserySiteId");

                    b.HasIndex("TreeTypeId");

                    b.ToTable("Zone", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "A1",
                            IsDeleted = false,
                            NurserySiteId = 1,
                            Size = 20m,
                            TreeTypeId = 1
                        });
                });

            modelBuilder.Entity("AP.BTP.Domain.EmployeeTask", b =>
                {
                    b.HasOne("AP.BTP.Domain.TaskList", "TaskList")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskListId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaskList");
                });

            modelBuilder.Entity("AP.BTP.Domain.Instruction", b =>
                {
                    b.HasOne("AP.BTP.Domain.TreeType", "TreeType")
                        .WithMany("Instructions")
                        .HasForeignKey("TreeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TreeType");
                });

            modelBuilder.Entity("AP.BTP.Domain.NurserySite", b =>
                {
                    b.HasOne("AP.BTP.Domain.Address", "Address")
                        .WithOne("NurserySite")
                        .HasForeignKey("AP.BTP.Domain.NurserySite", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AP.BTP.Domain.GroundPlan", "GroundPlan")
                        .WithOne("NurserySite")
                        .HasForeignKey("AP.BTP.Domain.NurserySite", "GroundPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AP.BTP.Domain.User", "User")
                        .WithOne("NurserySite")
                        .HasForeignKey("AP.BTP.Domain.NurserySite", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("GroundPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AP.BTP.Domain.TaskList", b =>
                {
                    b.HasOne("AP.BTP.Domain.User", "User")
                        .WithMany("TaskLists")
                        .HasForeignKey("UserId");

                    b.HasOne("AP.BTP.Domain.Zone", "Zone")
                        .WithMany("TaskLists")
                        .HasForeignKey("ZoneId");

                    b.Navigation("User");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("AP.BTP.Domain.TreeImage", b =>
                {
                    b.HasOne("AP.BTP.Domain.TreeType", null)
                        .WithMany("TreeImages")
                        .HasForeignKey("TreeTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AP.BTP.Domain.User", b =>
                {
                    b.HasOne("AP.BTP.Domain.NurserySite", "PreferredNurserySite")
                        .WithMany()
                        .HasForeignKey("PreferredNurserySiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PreferredNurserySite");
                });

            modelBuilder.Entity("AP.BTP.Domain.UserRole", b =>
                {
                    b.HasOne("AP.BTP.Domain.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AP.BTP.Domain.Zone", b =>
                {
                    b.HasOne("AP.BTP.Domain.NurserySite", "NurserySite")
                        .WithMany("Zones")
                        .HasForeignKey("NurserySiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AP.BTP.Domain.TreeType", "TreeType")
                        .WithMany("Zones")
                        .HasForeignKey("TreeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NurserySite");

                    b.Navigation("TreeType");
                });

            modelBuilder.Entity("AP.BTP.Domain.Address", b =>
                {
                    b.Navigation("NurserySite")
                        .IsRequired();
                });

            modelBuilder.Entity("AP.BTP.Domain.GroundPlan", b =>
                {
                    b.Navigation("NurserySite")
                        .IsRequired();
                });

            modelBuilder.Entity("AP.BTP.Domain.NurserySite", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("AP.BTP.Domain.TaskList", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AP.BTP.Domain.TreeType", b =>
                {
                    b.Navigation("Instructions");

                    b.Navigation("TreeImages");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("AP.BTP.Domain.User", b =>
                {
                    b.Navigation("NurserySite")
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("TaskLists");
                });

            modelBuilder.Entity("AP.BTP.Domain.Zone", b =>
                {
                    b.Navigation("TaskLists");
                });
#pragma warning restore 612, 618
        }
    }
}
